CREATE TABLE AUTHOR(
ID NUMBER,
CONSTRAINT AUTHOR_PK PRIMARY KEY (ID),
NAME NVARCHAR(50) NOT NULL,
LAST_NAME NVARCHAR(50) UNIQUE,
COUNTRY NVARCHAR(50) DEFAULT 'UKRAINE',
AGE NUMBER DEFAULT 0,
ARTICLES_COUNT NUMBER CHECK(ARTICLES_COUNT>10),
CONSTRAINT CHECK_COUNTRY CHECK (COUNTRY != 'CHINA' AND LAST_NAME != 'TEST_LN')
)