CREATE TABLE HOTEL(
ID NUMBER,
CONSTRAINT HOTEL_PK PRIMARY KEY (ID),
COUNTRY NVARCHAR(50) DEFAULT 'N/A',
CONSTRAINT CHECK_COUNTRY CHECK (COUNTRY != 'Romania' OR COUNTRY != 'Belgium' OR COUNTRY != 'China' OR COUNTRY != 'Ukraine' )
CITY NVARCHAR(50) NOT NULL,
STREET NVARCHAR(50)
)