CREATE TABLE ORDER(
ID NUMBER,
CONSTRAINT ORDER_PK PRIMARY KEY (ID),
CONSTRAINT CHECK_ORDER CHECK (ORDER_PK <= 10000 ),
USER_ID NUMBER UNIQUE,
ROOM_ID NUMBER UNIQUE,
DATE_FROM DATE,
DATE_TO DATE,
CONSTRAINT CHECK_DATE CHECK (DATE_FROM <= DATE_TO ),
MONEY_PAID  FLOAT(2)
)