SELECT DIRECTOR, COUNT (MOVIE_ID) FROM MOVIE
GROUP BY DIRECTOR;


SELECT DIRECTOR,SUM(DOMESTIC_SALES),SUM(INTERNATIONAL_SALES)
FROM MOVIE INNER JOIN MOVIE_STAT ON MOVIE.MOVIE_ID = MOVIE_STAT.MOVIE_ID
GROUP BY DIRECTOR;




SELECT *
FROM MOVIE
ORDER BY YEAR DESC;

SELECT *
FROM MOVIE_STAT
ORDER BY INTERNATIONAL_SALES DESC ;