CREATE TABLE MOVIE(
CONSTRAINT MOVIE_ID UNIQUE PRIMARY KEY,
TITLE NVARCHAR(50) UNIQUE NOT NULL,
DIRECTOR NVARCHAR(20) NOT NULL,
YEAR NUMBER CHECK (YEAR >= 1900  AND YEAR <= 2021 ),
LENGTH_MINS NUMBER CHECK (LENGTH_MINS >= 10 AND LENGTH_MINS <= 200 ),

)